barbeariaWeb/config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  #get 'home/index'
  #root :to => "home#index"

  #devise_for :users

  resources :usuarios

  def devise_path_names
    { sign_in: "login", sign_up: "", registration: "register", sign_out: "logout" }
  end
  devise_for :users,  path_names: devise_path_names #-> url.com/users/login
  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }, path_names: devise_path_names #-> url.com/admins/login
  #devise_for :admins, controllers: { sessions: "devise#sessions", registrations: "devise#registrations" }, path_names: devise_path_names #-> url.com/admins/login
  devise_scope :user do
    get 'users/login',  to: 'users#sessions#new',  as: 'user_login'
    #resources :produtos
    #resources :enderecos
    #resources :barbearia
     root :to => "home#index"
     get 'sobre', to: 'home#sobre'
     get 'contato', to: 'home#contato'
  end

  devise_scope :admin do
    get 'admins/login',  to: 'admins#sessions#new', as: 'admin_login'
    delete 'admins/logout', to: 'devise/sessions#destroy', as: 'admin_logout'
    resources :produtos
    resources :enderecos
    resources :barbearia
    root :to => "home#index"
    get 'sobre', to: 'home#sobre'
    get 'contato', to: 'home#contato'
  end
  #root :to => "home#index"
  #Usados de acordo com seus controllers
  #devise_for :users, path: 'users', controllers: { sessions: "users/sessions" etc....}



end

barbeariaWeb/app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'Todos os direitos reservados.',"#" %>
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to 'Sobre', sobre_path %>
      </li>
      <li>
        <%= link_to 'Contato', contato_path %>
      </li>
    </ul>
  </nav>
</footer>

barbeariaWeb/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
    <div class="collapse navbar-collapse" id="expanded-menu">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Barbearias', barbearia_path %>
          </li>
          <li>
            <%= link_to 'Produtos', produtos_path %>
          </li>
          <li>
            <%= link_to 'Usuarios', usuarios_path %>
          </li>
          <li>
            <%= link_to 'Endereços', enderecos_path %>
          </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li>
          <%= link_to 'Edit profile', edit_user_registration_path %>
          </li>
          <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
          <%= link_to "Cadastrar-se", new_user_registration_path %>
          </li>
          <li>
          <%= link_to "Entrar", new_user_session_path%>
          </li>
        <% end %>

      </ul>

    </div>

  </div>

</nav>

barbeariaWeb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barbearia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

  </body>

</html>