barbeariaWeb/config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  #get 'home/index'
  #root :to => "home#index"

  #devise_for :users

  resources :usuarios

  def devise_path_names
    { sign_in: "login", sign_up: "", registration: "register", sign_out: "logout" }
  end
  devise_for :users,  path_names: devise_path_names #-> url.com/users/login
  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }, path_names: devise_path_names #-> url.com/admins/login
  #devise_for :admins, controllers: { sessions: "devise#sessions", registrations: "devise#registrations" }, path_names: devise_path_names #-> url.com/admins/login
  devise_scope :user do
    get 'users/login',  to: 'users#sessions#new',  as: 'user_login'
    #resources :produtos
    #resources :enderecos
    #resources :barbearia
     root :to => "home#index"
     get 'sobre', to: 'home#sobre'
     get 'contato', to: 'home#contato'
  end

  devise_scope :admin do
    get 'admins/login',  to: 'admins#sessions#new', as: 'admin_login'
    delete 'admins/logout', to: 'devise/sessions#destroy', as: 'admin_logout'
    resources :produtos
    resources :enderecos
    resources :barbearia
    root :to => "home#index"
    get 'sobre', to: 'home#sobre'
    get 'contato', to: 'home#contato'
  end
  #root :to => "home#index"
  #Usados de acordo com seus controllers
  #devise_for :users, path: 'users', controllers: { sessions: "users/sessions" etc....}



end

barbeariaWeb/app/models/endereco.rb
class Endereco < ApplicationRecord
  validates :rua, presence: true, length: {maximum: 50}
  validates :bairro, presence: true, length: {maximum: 20}
  validates :numero, presence: true, length: {minimum: 1, maximum: 8}
  belongs_to :barbearium
end

barbeariaWeb/app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: [:show, :edit, :update, :destroy]

  # GET /enderecos
  # GET /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1
  # GET /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos
  # POST /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to @endereco, notice: 'Endereco was successfully created.' }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1
  # PATCH/PUT /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to @endereco, notice: 'Endereco was successfully updated.' }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1
  # DELETE /enderecos/1.json
  def destroy
    @endereco.destroy
    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: 'Endereco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endereco_params
      params.require(:endereco).permit(:rua, :bairro, :numero, :id, :barbearium_id)
    end
end

barbeariaWeb/app/helpers/enderecos_helper.rb
module EnderecosHelper
end

barbeariaWeb/app/views/enderecos/_form.html.erb
<%= form_with(model: endereco, local: true) do |form| %>
  <% if endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rua %>
    <%= form.text_field :rua, id: :endereco_rua %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :endereco_bairro %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :numero, id: :endereco_numero %>
  </div>

  <div class="field">
    <%= form.label 'Barbearia' %>
    <%= form.number_field :barbearium_id, id: :endereco_barbearium_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

barbeariaWeb/app/views/enderecos/edit.html.erb
<h1>Editing Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Show', @endereco %> |
<%= link_to 'Back', enderecos_path %>

barbeariaWeb/app/views/enderecos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Rua</th>
      <th>Bairro</th>
      <th>Numero</th>
      <th>Id</th>
      <th>Barbearia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= endereco.rua %></td>
        <td><%= endereco.bairro %></td>
        <td><%= endereco.numero %></td>
        <td><%= endereco.id %></td>
        <td><%= endereco.barbearium_id %></td>
        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

barbeariaWeb/app/views/enderecos/new.html.erb
<h1>New Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Back', enderecos_path %>

barbeariaWeb/app/views/enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rua:</strong>
  <%= @endereco.rua %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @endereco.bairro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @endereco.numero %>
</p>

<p>
  <strong>Id:</strong>
  <%= @endereco.id %>
</p>

<p>
  <strong>Barbearia:</strong>
  <%= @endereco.barbearium_id %>
</p>

<%= link_to 'Edit', edit_endereco_path(@endereco) %> |
<%= link_to 'Back', enderecos_path %> |
<%= link_to 'Destroy', @endereco, method: :delete, data: { confirm: 'Are you sure?' } %>