barbeariaWeb/config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  #get 'home/index'
  #root :to => "home#index"

  #devise_for :users

  resources :usuarios

  def devise_path_names
    { sign_in: "login", sign_up: "", registration: "register", sign_out: "logout" }
  end
  devise_for :users,  path_names: devise_path_names #-> url.com/users/login
  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }, path_names: devise_path_names #-> url.com/admins/login
  #devise_for :admins, controllers: { sessions: "devise#sessions", registrations: "devise#registrations" }, path_names: devise_path_names #-> url.com/admins/login
  devise_scope :user do
    get 'users/login',  to: 'users#sessions#new',  as: 'user_login'
    #resources :produtos
    #resources :enderecos
    #resources :barbearia
     root :to => "home#index"
     get 'sobre', to: 'home#sobre'
     get 'contato', to: 'home#contato'
  end

  devise_scope :admin do
    get 'admins/login',  to: 'admins#sessions#new', as: 'admin_login'
    delete 'admins/logout', to: 'devise/sessions#destroy', as: 'admin_logout'
    resources :produtos
    resources :enderecos
    resources :barbearia
    root :to => "home#index"
    get 'sobre', to: 'home#sobre'
    get 'contato', to: 'home#contato'
  end
  #root :to => "home#index"
  #Usados de acordo com seus controllers
  #devise_for :users, path: 'users', controllers: { sessions: "users/sessions" etc....}



end

barbeariaWeb/app/models/produto.rb
class Produto < ApplicationRecord
  validates :nome, presence: true, length: { minimum: 3, maximum: 50 }
  validates :valor, presence: true, numericality: { greater_than: 0}
  validates :quantidade, presence: true, numericality: { greater_than: -1 }
  belongs_to :barbearium
end

barbeariaWeb/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :valor, :quantidade, :barbearium_id)
    end
end

barbeariaWeb/app/helpers/produtos_helper.rb
module ProdutosHelper
end

barbeariaWeb/app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :produto_nome %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, id: :produto_descricao %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor, id: :produto_valor %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade, id: :produto_quantidade %>
  </div>

  <div class="field">
    <%= form.label 'Barbearia' %>
    <%= form.number_field :barbearium_id, id: :produto_barbearium_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

barbeariaWeb/app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

barbeariaWeb/app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Valor</th>
      <th>Quantidade</th>
      <th>Barbearia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.descricao %></td>
        <td><%= produto.valor %></td>
        <td><%= produto.quantidade %></td>
        <td><%= produto.barbearium_id %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

barbeariaWeb/app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

barbeariaWeb/app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @produto.valor %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto.quantidade %>
</p>

<p>
  <strong>Barbearia:</strong>
  <%= @produto.barbearium_id %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>
<%= link_to 'Destroy', @produto, method: :delete, data: { confirm: 'Are you sure?' } %>